[build]
  command = "yarn build"
  publish = "./build"
  functions = "./functions"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/d/*"
  to = "/d/index.html"
  status = 200

[[redirects]]
  from = "/h/*"
  to = "/h/index.html"
  status = 200

[[redirects]]
  from = "/m/*"
  to = "/m/index.html"
  status = 200

[[redirects]]
  from = "/di/*"
  to = "/di/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js" # Cache JS files for long period
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css" # Cache CSS files for long period
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg" # Cache JPEG files for long period
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png" # Cache PNG files for long period
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp" # Cache WEBP files for long period
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/sw.js" # Cache Service Worker file
  [headers.values]
    Cache-Control = "public, max-age=0"
