backend:
  name: test-repo

media_folder: "web/images/uploads"
media_library:
  name: uploads

show_preview_links: false

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Doujinshi Pages"
        name: "doujinshi"
        file: "json/doujinshi.json"
        fields:
          - label: Books
            name: book
            widget: list
            fields:
              - { label: Book, name: book, widget: linkScraper }
