backend:
  name: github
  repo: imouto1994/Fumino

media_folder: "web/images/uploads"
media_library:
  name: uploads

show_preview_links: false

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Doujinshi Page"
        name: "doujinshi"
        file: "json/doujinshi.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
      - label: "Hentai Page"
        name: "hentai"
        file: "json/hentai.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
      - label: "Manga Page"
        name: "manga"
        file: "json/manga.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
      - label: "Digital Pages"
        name: "digital"
        file: "json/digital.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
