backend:
  name: github
  repo: imouto1994/Fumino
  squash_merges: true
  commit_messages:
    update: Update collection {{collection}}

publish_mode: editorial_workflow

media_folder: "web/images/uploads"

show_preview_links: false

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "/d Page"
        name: "d"
        file: "json/d.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
      - label: "/h Page"
        name: "h"
        file: "json/h.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
      - label: "/m Page"
        name: "m"
        file: "json/m.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
      - label: "/di Pages"
        name: "di"
        file: "json/di.json"
        fields:
          - label: Books
            name: books
            widget: bookFetch
